          sed -i 's#^distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.6-all.zip#' android/gradle/wrapper/gradle-wrapper.properties

      - name: Patch AGP & Kotlin
        run: |
          sed -i 's/com.android.tools.build:gradle:[^"]*/com.android.tools.build:gradle:8.3.2/' android/build.gradle
          sed -i 's/kotlin-gradle-plugin:[^"]*/kotlin-gradle-plugin:1.9.24/' android/build.gradle

      - name: Ensure publishing singleVariant in app/build.gradle
        run: |
          if ! grep -q 'singleVariant(\"release\")' android/app/build.gradle; then
            awk '/^android\\s*{/{print;print \"  publishing {\\n    singleVariant(\\\"debug\\\")\\n    singleVariant(\\\"release\\\")\\n  }\";next}1' android/app/build.gradle > android/app/build.gradle.tmp
            mv android/app/build.gradle.tmp android/app/build.gradle
          fi

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

